CREATE TABLE employees (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    role VARCHAR(20)  NOT NULL
);

CREATE TABLE shifts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees (id),
    shift_date  DATE   NOT NULL,
    start_time  TIME   NOT NULL,
    end_time    TIME   NOT NULL
);

CREATE INDEX idx_shifts_employee_id ON shifts (employee_id);

CREATE TABLE swap_requests (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id        BIGINT       NOT NULL REFERENCES employees (id),
    requester_shift_id  BIGINT       NOT NULL REFERENCES shifts (id),
    target_employee_id  BIGINT       NOT NULL REFERENCES employees (id),
    target_shift_id     BIGINT       NOT NULL REFERENCES shifts (id),
    status              VARCHAR(20)  NOT NULL,
    reason              VARCHAR(500),
    decided_by_id       BIGINT REFERENCES employees (id),
    decision_note       VARCHAR(500),
    created_at          TIMESTAMP    NOT NULL,
    decided_at          TIMESTAMP
);

CREATE INDEX idx_swap_requests_status ON swap_requests (status);
CREATE INDEX idx_swap_requests_requester_id ON swap_requests (requester_id);
CREATE INDEX idx_swap_requests_target_employee_id ON swap_requests (target_employee_id);
